### ISSUE TITLE
Changing text for monitoring

### ISSUE THREAD

**Issue by ghumman96** [OHSUCMP/coach#104]
Current version "Consider obtaining additional blood pressure measurements.
Since we do not have enough blood pressure measurements to obtain a full picture of your health, we recommend you take a full set of measurements. We consider a full set to be more than 4 in-office measurements, 6 home measurements, or 24 hours of ambulatory monitoring."

We need to change to 

"Since we do not have enough blood pressure measurements to obtain a full picture of your health, we recommend you take a full set of measurements. We consider a full set to be more than 12 home measurements."

**Comment by aeyates** [comment]
This is completed and available to see on the sandbox. See patient "WeightLoss Achieved" for an example.
