### ISSUE TITLE
implement Clinician view

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#106]
we need to implement a clinician view of COACH that notably does the following:

- bypasses REDCap (no consent requirements, etc.)
- shows intervention view of COACH

there might be some other things that need adding to this but I think this is it, definitely enough to get moving on this

**Comment by aeyates** [comment]
dd will add details

**Comment by aeyates** [comment]
@MichelleBobo The last comment before yours was from our meeting 2 weeks ago. @davedorr9 was supposed to add implementation details to the ticket so we could move forward.

**Comment by davedorr9** [comment]
Clinician view
By site (vanderbilt, OHSU, and Missouri), do different things.
Vanderbilt : if not consented, show consent page; if consented, show full COACH (intervention version)
OHSU : show full COACH no matter consent status
Missouri : unknown

**Comment by aeyates** [comment]
@davedorr9 You want Vanderbilt clinicians to go through REDCap consent? Is there some different consent process for them I'm unaware of? Something outside of REDCap? Please provide more detail.

**Comment by davedorr9** [comment]
@aeyates  No, they should see the PATIENT consent page telling them this patient isn't consented.

**Comment by davedorr9** [comment]
Within REDCap

**Comment by aeyates** [comment]
If we send them to the patient consent page, then they can consent as the patient and fill out all the forms to get randomized into the study. Is this really what you want?

**Comment by davedorr9** [comment]
They will not consent the patient. They will know the patient isn't consented and either show the screen to the patient to consent themselves or will refer the patient for consent.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Amy Yates ***@***.***>
Sent: Wednesday, November 22, 2023 1:11:15 PM
To: OHSUCMP/coach ***@***.***>
Cc: David Dorr ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OHSUCMP/coach] implement Clinician view (Issue #106)


If we send them to the patient consent page, then they can consent as the patient and fill out all the forms to get randomized into the study. Is this really what you want?

**Comment by aeyates** [comment]
Additional context from today's discussion. VUMC wants to make sure that the clinician does not get access to COACH until the patient has consented, so this is why their flow needs to be a little different. I would suggest we not forward the clinician to the consent process in REDCap though. It's not just a single page, it's a whole flow designed for use by a patient. Instead, the clinician could be forwarded to a page letting them know that we are waiting on participant consent. Once we have it, the clinician would see the enhanced view like OHSU does.

**Comment by mattStorer** [comment]
just spoke with Dave about the MU workflow.  theirs should work the same as OHSU's, which is to say, show the intervention view, whether or not the patient has consented.  VUMC is the only outlier in this respect.  also, Dave confirmed that the proposed VUMC strategy of displaying a static "patient not consented" page is good, instead of sending them to the REDCap workflow.

**Comment by mattStorer** [comment]
clinician view development is code complete and pushed to develop branch.

clinician view is identified based on the client ID used to launch COACH.  there really isn't another good way to identify this, as the redirect URI for both patient and client launches is the root "/" path, which brings the flow of logic into the `fhir-complete-handshake` template, which itself passes SMART-on-FHIR objects (such as `clientId`) via AJAX to `SessionController.prepareSession`, and it is within that function that the _Audience_ is determined (`PATIENT`, `CARE_TEAM`).  This, taken in conjunction with the _RedcapDataAccessGroup_ value (a new `enum` that replaces the usage of static strings, with values `OHSU`, `MU`, and `VUMC`) is used to determine a) if the flow needs to go to REDCap (if `PATIENT` and not consented), or if REDCap should be skipped (`CARE_TEAM`), and what to display in that case, i.e. the enhanced view of COACH (for `OHSU` and `MU`), or a static "patient not yet consented" page (for `VUMC`)
