### ISSUE TITLE
check Patient deceased info when pulling Patient resource

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#111]
we need to augment COACH to ensure that it [something] when encountering a deceased Patient.  check `deceasedBoolean` and / or `deceasedDateTime` on load, and [something] in that case.

// todo : identify what [something] is precisely.  it's probably something along the lines of "prohibit access" but this should be properly defined before implementation.

**Comment by davedorr9** [comment]
Ask whomever is logging in to report this to the study team using a link to the redcap AE.

**Comment by aeyates** [comment]
Resolved with no code changes needed.
