### ISSUE TITLE
AE language changes

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#112]
Mockup:

https://ohsuitg-my.sharepoint.com/:p:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/Mockups%20and%20Screenshots/Cases%20Mockups/AE%20Mockup.pptx?d=w61796638c7ee4abdad9f69e0301e7012&csf=1&web=1&e=yuEDHC

Mention of "adverse event" should be changed to "side effect" everywhere.

**Comment by aeyates** [comment]
Rec 34 language was agreed on and is in the document. In this case, we will not provide a link to a Care Team message.

**Comment by aeyates** [comment]
@ghumman96 The requirements documents are not clear and do not address all the possible language that can be in a recommendation (header, body, suggestions, links.) Here are screenshots of what I implemented. I had to make some of it up. Can you review and let me know if changes need to be made?

Scenario 1: (Rec 33) Patient had 2 adverse events in the last month and has not indicated they've contacted their care team:

<img width="1053" alt="Untreated" src="https://github.com/OHSUCMP/coach/assets/2576491/8b6691a4-012d-49bd-8982-25e35370b0ee">

Scenario 2: (Rec 33 and 34) Patient had 2 adverse events in the last month and has indicated they contacted their care team about one of them:

<img width="1053" alt="treated and untreated" src="https://github.com/OHSUCMP/coach/assets/2576491/a517bcf4-dce6-439e-b1de-8f3e0ae495df">

Scenario 3: (Rec 34) Patient has 2 adverse events in the last month and has indicated they contacted their care team about both:

<img width="1049" alt="treated" src="https://github.com/OHSUCMP/coach/assets/2576491/e2ecdd32-0aea-4af4-888c-ffac6aa05056">

**Comment by ghumman96** [comment]
@aeyates It looks good to me and makes sense. No changes are required at this time. I would remove the period after "see care team and discuss treatment if event recurs" it looks awkward.
