### ISSUE TITLE
Contact Message instructions reference MyChart/OHSU

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#124]
These instructions need to be made generic instead of referring participants to OHSU's MyChart instance:

<img width="723" alt="Screen Shot 2023-12-01 at 1 53 07 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/d97ff537-aeaf-4d3a-8cd6-234b07450396">

**Comment by aeyates** [comment]
To reproduce:

- Go to patient Untreated Adverse Event. 
- In Recommendations, click on "Contact my care team"
- On the Contact Message page, click "Copy and Paste"

**Comment by aeyates** [comment]
These instructions should work for Vanderbilt since the direct link is configurable. However, MU uses Cerner and MyHealth, so their instructions are different. Here are the instructions sent by Emma Montgomery and Richelle. Most of the language is the same, but some swapping is needed:

1. Log into HealthConnect
2. Go to the Messages tab at the top left, click “send a message”
3. It will give you pre-populated options to select from. DO NOT select these, scroll to the bottom and select “message your care team”
4. Under “To”, select the Care Team member that gave you access to this Application (you can give permission for others to view this message if you wish)
5. Specify an appropriate Subject
6. Paste (Ctrl-V, or right click and select “Paste”) this message into the HealthConnect message text-area
7. Review the message and edit as desired
8. When everything looks complete and correct, click “Send”
 
Here is the link to the MU Health Care accessing your account page: [https://www.muhealth.org/patient-login](https://urldefense.com/v3/__https://www.muhealth.org/patient-login__;!!Mi0JBg!L62e-PbS3cOitfdpi8qMt1HnoV6ulx6IsB5CekcEeIIs5e0xGHM_LyGMOIiccnQjsKHGt1gLBtBrljelhXHTgpRvYQh8KLU$)
Here is the link to the HealthConnect portal login: [https://muhealth.consumeridp.us-1.healtheintent.com/saml2/sso/login?authenticationRequestId=12a3a288-16db-4a4f-9731-f3edb9d63734](https://urldefense.com/v3/__https://muhealth.consumeridp.us-1.healtheintent.com/saml2/sso/login?authenticationRequestId=12a3a288-16db-4a4f-9731-f3edb9d63734__;!!Mi0JBg!L62e-PbS3cOitfdpi8qMt1HnoV6ulx6IsB5CekcEeIIs5e0xGHM_LyGMOIiccnQjsKHGt1gLBtBrljelhXHTgpRvTgdLad4$)

**Comment by aeyates** [comment]
@mattStorer This issue was discovered during 1.5.0 testing and needs to be fixed before we release. Can you take a look? The solution should be merged into master, not develop, since it's part of 1.5.0.

**Comment by mattStorer** [comment]
> @mattStorer This issue was discovered during 1.5.0 testing and needs to be fixed before we release. Can you take a look? The solution should be merged into master, not develop, since it's part of 1.5.0.

@aeyates ah yes that makes sense.  I'll fix this and merge to master.

**Comment by mattStorer** [comment]
this is fixed and pushed to master.  note that there is a new property `contact.instructions-html` in _application.properties_ which eclipses and replaces `mychart.login.url` and `mychart.askAMedicalQuestion.url`.  this is a generic solution that will allow each implementation to specify, in very granular detail, whatever they like for these instructions.

**Comment by aeyates** [comment]
I deployed this to the sandbox and confirmed there.
