### ISSUE TITLE
Care Team Messages BP Calculation

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#127]
The calculation for readings in the last X days is not correct. In the sandbox, patient Untreated Adverse Event is listed as having 4 readings in the last 0 days:

<img width="1314" alt="Screen Shot 2023-12-04 at 10 06 18 AM" src="https://github.com/OHSUCMP/coach/assets/2576491/c09ce673-7ccc-4af0-800c-84b046e506ef">

And here is their list of BPs:

<img width="1312" alt="Screen Shot 2023-12-04 at 10 06 57 AM" src="https://github.com/OHSUCMP/coach/assets/2576491/69eaeec4-a1c6-484b-9b59-8f24d87fb334">

All 4 readings were on the same day but three weeks ago, so maybe this is the confusion? @mattStorer Can you take a look?

**Comment by mattStorer** [comment]
@aeyates curious!  yes I will dig into this for sure, thanks for bringing this to my attention!

**Comment by mattStorer** [comment]
this should be working correctly now.

tested with Untreated AdverseEvent locally.  these are their home BP readings (including 2 readings on each day 11/16 and 11/17, 4 readings total)

![image](https://github.com/OHSUCMP/coach/assets/979938/8b1e9934-4b5e-48d2-a5ea-a083867c4c89)

this is what their graph looks like:

![image](https://github.com/OHSUCMP/coach/assets/979938/b0d5c7e7-956f-440c-863b-9779b9eac6d8)

and this is what their care-team message now reads:

![image](https://github.com/OHSUCMP/coach/assets/979938/6f576c93-74a8-43f2-ab94-e2e4851a1d13)

today is 12/8.  the most recent home BP reading within the last 30 days was taken on 11/16, which was 22 days ago.

**Comment by aeyates** [comment]
This issue was discovered during 1.5.0 testing, so it needed to be merged into master. I cherry-picked and pushed to the sandbox.
