### ISSUE TITLE
Update the protocol and Language on second measurement

### ISSUE THREAD

**Issue by ghumman96** [OHSUCMP/coach#141]

**Comment by ghumman96** [comment]
[Protocol](https://ohsuitg.sharepoint.com/:b:/r/sites/PROJ.COACH/Shared%20Documents/General/3-2%20COACH%20build/Infographics/Blood%20Pressure%20Measurement%20Instructions.pdf?csf=1&web=1&e=vkTxQU)

**Comment by ghumman96** [comment]
![image](https://github.com/OHSUCMP/coach/assets/142044765/b96fcfd9-1992-4f03-a5ea-85999caafceb)

**Comment by aeyates** [comment]
Merged to develop branch
