### ISSUE TITLE
VUMC: Clinician cannot see patient after they have consented

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#149]
Patient "H-ExcludedUnder18" has consented in REDCap but not yet completed the other surveys or been randomized. When a clinician logs in, they get the message that the patient hasn't consented:

<img width="1036" alt="consent" src="https://github.com/OHSUCMP/coach/assets/2576491/7071dbed-5fb2-4d99-8c5d-a12eaf2599e7">

**Comment by aeyates** [comment]
I have examined the code, and it looks like @mattStorer is checking whether the patient is actively enrolled rather than whether or not they have consented. I think this might actually be better, since it would also have the effect of preventing clinicians from viewing a patient if they have withdrawn from the study. @davedorr9 Is this an acceptable solution for VUMC? Should the language be changed on the page the clinician sees to indicated the patient is not actively enrolled instead?

**Comment by davedorr9** [comment]
Either is fine. But the text should match the situation - so change to 'enrolled' and go for it.

**Comment by aeyates** [comment]
@mattStorer Let's go with the following language:

**Patient Not Active in Study**

The patient you are attempting to view is not actively enrolled in the study. This may be because they have not completed the enrollment process or because they have withdrawn from the study.

If you believe you are seeing this message in error, you or the patient can contact the study staff at COACH-OHSU@ohsu.edu.

Thank you.

**Comment by aeyates** [comment]
New screenshot:

<img width="1307" alt="Screen Shot 2023-12-20 at 3 32 22 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/03d84e82-732b-4df2-b556-db5a2377ff47">

**Comment by aeyates** [comment]
This was pushed to the sandbox and tested.
