### ISSUE TITLE
Omron integration - only sync data up to 30 days before randomization date.

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#151]
When a user synchronizes with Omron, the system synchronizes vitals that were created since the last synchronize operation occurred.  This "last synchronized" timestamp isn't set the first time a user synchronizes, and so all vitals are retrieved that exist at that time.

This makes sense and is conceptually fine, but it may not be how we want things to work in the COACH study.

Do we want to set a starting timestamp, such that vitals are only ever retrieved after that time?  Perhaps 2 years back, or 5?  Perhaps the date they enrolled in COACH?  Perhaps a statically defined date representing the start of the COACH study?  Something else?

**Comment by aeyates** [comment]
Only get -30 days from randomization date.

**Comment by aeyates** [comment]
@mattStorer RedcapParticipantInfo has been updated to provide the randomizationDate. Note that you should check to see if REDCap is enabled before using this date to sync with OMRON. If REDCap is not enabled, I think you could just go back 30 days from "today"?

**Comment by mattStorer** [comment]
this is resolved and pushed to develop
