### ISSUE TITLE
Instructional and FAQ pages for COACH

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#45]
need to show instructions of some sort

**Comment by aeyates** [comment]
FAQ page that is a pdf instead - add to resources tab. Different for control vs intervention.

**Comment by aeyates** [comment]
There will be an instructions page that will be different for control/experimental. The FAQ page is separate and will probably be the same for both.

**Comment by MichelleBobo** [comment]
Hi all,
This item is labeled needs info. Can you clarify what is needed here? Are you just waiting for the document from Aisha? Or is there logic that needs clarified? Can we move the coding forward with a placeholder document that can be revised as needed?

**Comment by mattStorer** [comment]
@MichelleBobo The document from @ghumman96 is one thing we'll need for sure, but also we need to establish / clarify the how, where, and when we want it to be displayed.

the title of the ticket states "on first login," but no other information is available to refine that.  without other guidance, I'm envisioning a modal popup that appears over the homepage with the specified text, that the user can close with a button, and once closed it doesn't reappear on subsequent logins.

does this track with your understanding?

**Comment by aeyates** [comment]
I believe we discussed this in a meeting a couple of weeks ago and are not going to have any specific instructions "on first login". @ghumman96 is developing documentation or a video as part of the onboarding process that will cover that. So we should change this title. The instructional material will just be another link under the resources tab, and as mentioned it will be different depending on whether they are control or enhanced. But there is no point in moving forward with an empty link - we need the material before we incorporate it.

**Comment by aeyates** [comment]
FAQ document: https://teams.microsoft.com/l/message/19:028e8c5d-836e-4d57-b6fc-4c5abb8a68e6_5aa5f264-84d2-4eba-b1c2-44e15bb06452@unq.gbl.spaces/1701209241722?context=%7B%22contextType%22%3A%22chat%22%7D

**Comment by aeyates** [comment]
I made a few adjustments to the document provided for better clarity. I also eliminated the instructions for what to do if they can't log in. They can't see the page if they can't log in.
