### ISSUE TITLE
explore using Liquibase as a schema-agnostic method for applying database updates

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#51]
Vanderbilt team suggested using [Liquibase](https://www.liquibase.org/) as a mechanism to define a database schema in a DBMS-agnostic manner, which can be applied to any target DBMS.

Sounds like there's a bit of a learning curve, so something good to explore perhaps when we have some free time.

**Comment by mattStorer** [comment]
[Flyway](https://flywaydb.org/) would also probably do the trick

**Comment by aeyates** [comment]
Flyway was integrated.
