### ISSUE TITLE
Add Symptoms page for calling 911

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#62]
https://ohsuitg-my.sharepoint.com/:i:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/Infographics/Symptoms%20to%20call%20911.png?csf=1&web=1&e=Gr0hMA

**Comment by mattStorer** [comment]
the text reads "Call 911 if your blood pressure is 180/120 mm Hg or greater and you have the following symptoms:
- Chest pain
- Shortness of breath
- Confusion
- Numbness or tingling
- Seizures
- Blurred vision
- Trouble speaking"

This text "and you have the following symptoms" is confusing, because it implies *all* of the following symptoms, but I think it actually means *any* of the following symptoms.

This is a really crucial aspect to be really clear on, and we're not being clear about it here.

Does someone need to exhibit all of these symptoms, or just one of them?  Or two?  How many of these symptoms does someone need to experience for them to need to call 911?

**Comment by aeyates** [comment]
This is a good observation @mattStorer . We also need to get clarity on whether the criteria is > 180/120 or >= 180/120. It was all over the map between language and logic in COACH and CQL. I tried to move everything to "strictly greater than", which is how it was defined in the original workflow diagrams, but here's another example where the language reads >=.

**Comment by mattStorer** [comment]
Additionally, the text at the bottom refers to an AHA page, but it's not a link, just underlined text.  if I search for that text on the internet, the top result is this:

https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/hypertensive-crisis-when-you-should-call-911-for-high-blood-pressure

which reads as follows:

> ### Hypertensive Urgency
> 
> If your blood pressure is 180/120 or greater, wait about five minutes and try again to take a reading. If the second reading is just as high and you are not experiencing any other associated symptoms of target organ damage such as chest pain, shortness of breath, back pain, numbness/weakness, change in vision or difficulty speaking, this would be considered hypertensive urgency. Your health care professional may just have you adjust or add medications, but this situation rarely requires hospitalization.
> ### Hypertensive Emergency
> 
> If your blood pressure reading is 180/120 or greater and you are experiencing any other associated symptoms of target organ damage such as chest pain, shortness of breath, back pain, numbness/weakness, change in vision or difficulty speaking, this would be considered a hypertensive emergency. Do not wait to see whether your pressure comes down on its own. Call 911.

so this page clearly identifies *any* of the following symptoms as being triggering criteria for calling 911.

HOWEVER, this list that they specify on this page *is different* from the list we provide - that is, there is significant overlap which is good, but we include some things that they don't (e.g. seizures), and they provide some things that we don't (e.g. back pain).

I think we need to resolve these discrepancies before finalizing this ticket.

**Comment by mattStorer** [comment]
@aeyates thanks.  I believe that the criteria is >= 180/120, per the text "If your blood pressure is 180/120 or greater" in the heart.org page I referenced above

**Comment by aeyates** [comment]
Perhaps, but that was not how it was worded or implemented in other parts of the application including the original requirement: https://build.fhir.org/ig/OHSUCMP/htnu18ig/branches/master/flow-very-high-bp.html Once we know what is correct, there are about a half dozen locations where it needs to be changed.

**Comment by aeyates** [comment]
This is the link in the CQL: https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/hypertensive-crisis-when-you-should-call-911-for-high-blood-pressure It's the same one you googled.

**Comment by aeyates** [comment]
Criteria question was addressed in #73 . After meeting on 8/17, it was decided to simply add the "any" language to the page with no other changes.

**Comment by mattStorer** [comment]
here's what it looks like
![image](https://github.com/OHSUCMP/coach/assets/979938/5d5bd924-71be-45ab-b02e-c2351f226ea8)
