### ISSUE TITLE
Menu Item for Help and Counseling pages

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#63]
Add a help section that provides all the links in the app including Counseling pages. This should be available to both intervention and control. 8/17 discussion

**Comment by mattStorer** [comment]
to be clear, this Help section should include help topics including, but not limited to, Counseling

**Comment by aeyates** [comment]
I'm not sure we have requirements around "Help" yet, but it seems a bit different than providing quick links to general resources. For now, I've added a Resources navigation link and added the pages I know of, including the new "Side Effects List" page. We can either add an additional section to this for Help or another Nav Link.

<img width="1552" alt="Screen Shot 2023-10-25 at 2 32 16 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/20bb90cc-3965-4a88-8310-f815e60f3f70">
