### ISSUE TITLE
Control Group - Home Page

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#64]
- Should not see traffic lights/stop sign in top section
- Only recommendations for High BP and Adverse events
- No graph - instead show the most recent BP if one exists
- If the BP is very high, show the text like we do for the trial group
- Add a link to the full BP list (for both control and experiemental?)

**Comment by MichelleBobo** [comment]
![image](https://github.com/OHSUCMP/coach/assets/147000980/aa71f88d-d5aa-40d8-a099-5a35a4e723c4)

On the goals page there is still a listing for "My Other Goals" with no way to interact or add anything. This seems a little awkward. is it possible to remove that text/section?

**Comment by aeyates** [comment]
@mattStorer See testing notes from Michelle. I'm reopening.

**Comment by mattStorer** [comment]
@aeyates @MichelleBobo the "My Other Goals" section populates as a result of user interactions with social goals generated by recommendation workflows.

See:
![goals](https://github.com/OHSUCMP/coach/assets/979938/5c7bb5c3-33f9-47f2-b06e-ba04772a6ef8)

**Comment by mattStorer** [comment]
I do agree that having a header with no other information is a little clunky.  I might suggest that we add some text below that header, saying something to the effect of "No other goals at this time.  These goals are generated as a result of interactions with recommendation workflows." or something along those lines.

Thoughts?

**Comment by aeyates** [comment]
Michelle is saying that people with the Control view should not see the header because they do not receive these recommendations for setting other types of goals.

**Comment by MichelleBobo** [comment]
I thought they weren't going to get recommendations to make goals in the Control workflow?

**Comment by mattStorer** [comment]
yes I'm just seeing that this was a control-group specific thing.  since those recommendations aren't set for control-group, we can remove these other goals section in that context, that makes sense.  apologies for not catching that part initially

**Comment by mattStorer** [comment]
fixed; now only showing _Other Goals_ if the user is in the `ENHANCED` randomization group
