### ISSUE TITLE
Participant report of AEs

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#66]
We may want to introduce a link in COACH to the REDCap AE Survey that a participant could fill out at any time if they are experiencing one of the symptoms.

**Comment by aeyates** [comment]
Discussed in 8/16-8/17 meetings. REDCap will have an AE form available to collect additional info from subjects when an AE occurs. The COACH recommendation should tap into this so that when a condition is detected, the participant is invited to complete the survey.

**Comment by MichelleBobo** [comment]
Can COACH see the REDCap AE form? Ask Amy when she returns. Review at next week's Tuesday meeting. Care team message or reporting form?

**Comment by aeyates** [comment]
https://ohsuitg-my.sharepoint.com/:p:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/Mockups%20and%20Screenshots/Cases%20Mockups/AE%20Mockup.pptx?d=w61796638c7ee4abdad9f69e0301e7012&csf=1&web=1&e=vsOOGs

**Comment by aeyates** [comment]
To clarify, this ticket only covers the work to add a link to REDCap AE form in COACH if the team decides they want to. The recommendation language changes for side effects are covered here: https://github.com/OHSUCMP/htnu18ig/issues/193

**Comment by aeyates** [comment]
@ghumman96 will provide the new language.

**Comment by ghumman96** [comment]
[https://ohsuitg.sharepoint.com/:p:/r/sites/PROJ.COACH/Shared%20Documents/General/3-2%20COACH%20build/Mockups%20and%20Screenshots/Cases%20Mockups/AE%20Mockup%20%5BAutosaved%5D.pptx?d=wef42e8acd1ab492ebdcd29b8f05cb6a1&csf=1&web=1&e=epLDZU](url)

**Comment by ghumman96** [comment]
**Report Potential Side Effects Associated with Blood Pressure Management**
A few key side effects are often related to hypertension treatment. [Click for complete list](https://ohsuitg.sharepoint.com/:i:/r/sites/PROJ.COACH/Shared%20Documents/General/3-2%20COACH%20build/Infographics/AE%20List.png?csf=1&web=1&e=bmie1l). Please make sure to talk to your doctor if you have these conditions or if you are concerned about your blood pressure. You can also inform the study team through this link.
Whenever you visit the emergency department or stay in the hospital, please let your doctor **and** the study team know, as we need to monitor certain events as part of the study.

**Comment by ghumman96** [comment]
@aeyates is the side effects list under resources updated yet? I was on sandbox and it's showing the older version under resources.

**Comment by aeyates** [comment]
No, this ticket will be closed when the update is made.

**Comment by aeyates** [comment]
@ghumman96 According to this screenshot, you've changed the link at the bottom of the side effects list. It used to go to the When to Call 911 page. Is this really what you want? The new link doesn't have anything to do with adverse events/side effects.

<img width="951" alt="Screen Shot 2023-12-13 at 10 40 52 AM" src="https://github.com/OHSUCMP/coach/assets/2576491/36046dad-08ff-4043-831f-d58e1c740d54">

**Comment by ghumman96** [comment]
[https://ohsuitg.sharepoint.com/:i:/r/sites/PROJ.COACH/Shared%20Documents/General/3-2%20COACH%20build/Infographics/AE%20List.png?csf=1&web=1&e=kQJkgF](url) Lets do this one

**Comment by aeyates** [comment]
This is now in the sandbox.

<img width="1312" alt="ae_link" src="https://github.com/OHSUCMP/coach/assets/2576491/95891b89-91e9-4419-874b-895a4a4c1b23">

<img width="914" alt="side-effects" src="https://github.com/OHSUCMP/coach/assets/2576491/e29c9fd1-0f43-41e3-a93c-3def95efe8e3">
