### ISSUE TITLE
Add info tooltip to stoplight

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#67]
The screenshots show an info tooltip next to the stoplight/stop sign that is supposed to provide more context on what those things mean. Aisha has developed some material but it is not finalized. It's a huge amount of information, so may not be appropriate for a tooltip.

**Comment by mattStorer** [comment]
https://ohsuitg-my.sharepoint.com/:w:/r/personal/yateam_ohsu_edu/Documents/Microsoft%20Teams%20Chat%20Files/Stop%20Light%20Interpretive%20(1).docx?d=w891c06e9614a407e855b803a4727d1e4&csf=1&web=1&e=JEJFCY

**Comment by mattStorer** [comment]
this document contains working-copy / non-finalized text intended to be associated with the stoplight icons as tooltips

[Stop Light Interpretive.docx](https://github.com/OHSUCMP/coach/files/12352635/Stop.Light.Interpretive.docx)

**Comment by aeyates** [comment]
Short text:

Green light: Your average BP is at goal. Average is calculated based on a maximum of 12 recent readings. Check the help tab to learn more about what to do.

Yellow Light: Your average BP is above goal. Average is calculated based on a maximum of 12 recent readings. Check the help tab to learn more about what to do.

STOP: Your most recent BP is very high. Check the help tab to learn more about what to do.

**Comment by aeyates** [comment]
Merged to develop
