### ISSUE TITLE
Add language for contact expectations

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#72]
Ensure patients know that the care team in not monitoring messages in real time. Can borrow language from here:

https://www.ohsu.edu/healthcare-now/mychart-messages

**Comment by aeyates** [comment]
"For urgent medical questions, call your clinic. Call 911 if this is an emergency. Average response time is 2-3 business days."

**Comment by davedorr9** [comment]
DOES THIS STILL NEED INFO?

**Comment by aeyates** [comment]
@davedorr9 We left the "Needs Info" until you approved the language in the comment. If you're good with it, we can remove the label and work on it. Language:

"Average response time is 2-3 business days. For urgent medical questions, call your clinic or call 911 if this is an emergency."

**Comment by davedorr9** [comment]
I've asked the team to not have me be the final approver on every language decision. So for all language / text related components, if Aisha says the team decided on xx, that's fine.
