### ISSUE TITLE
Care Team Messages rewrite

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#74]
Team will provide new messages that may have dynamic fields.

**Comment by davedorr9** [comment]
Above is the file -

**Comment by davedorr9** [comment]
X = home BPs in the last 30 days; Y = today - date last BP measure in days or 30 days, whichever is less; Average is average from the home page (same logic)

**Comment by aeyates** [comment]
This is not ready to be worked on. @mattStorer There is still some wordsmithing to be done for other care team messages, and we need to discuss the dynamic content and whether we can support it.

**Comment by mattStorer** [comment]
it was decided this morning that automatic personalization by way of token replacements should not be done to recommendations or any aspects relating to CQL-based evaluation, and should only occur within the context of care team messages.

> I collected {X} BP readings over {Y} days, my blood pressure is still above goal; my BP average is {SBP average} / {DBP average}.  What steps would you like me to take next?

this message obviously doesn't exist yet, and it's not precisely defined.  is this to replace an existing message (below), or are we crafting a new message for a new workflow endpoint?  these are our current contact messages that pertain to BP being above goal:

<HTML>
<BODY>
<TABLE><TR><TD>recommend-pharma-and-nonpharma</TD><TD>Blood pressure readings are substantially above goal. Lifestyle change counseling and antihypertensive medication were recommended.</TD><TD>The set of blood pressures recorded is substantially above goal. A combination of pharmacologic and non-pharmacologic treatment is recommended to better control blood pressure. This message was generated by the COACH tool and actively sent by the patient.</TD></TR><TR><TD>recommend-nonpharma</TD><TD>Blood pressure readings are above goal. &nbsp;Lifestyle change counseling, followed by treatment with antihypertensive medication was recommended.</TD><TD>This person had high blood pressures and was recommended to select from a set of behavior and lifestyle changes. They will be recommended to follow-up after they work on their goals to consider changing medications. This message was generated by the COAC...</TD></TR><TR><TD>recommend-pharma</TD><TD>Blood pressure is above goal after lifestyle changes. Treatment with antihypertensive medication is recommended.</TD><TD>Blood pressure readings are substantially above goal. Antihypertensive medication will be needed to lower blood pressure and meet goal. Discussing potential medication options and blood pressure goals with patient may be warranted. This message was gener...</TD></TR><TR><TD>recommend-advancing-treatment</TD><TD>Blood pressure remains above goal despite treatment. Additional antihypertensive treatment may be considered.</TD><TD>Blood pressure remains above goal despite current treatment. Changes to medication regimen, possibly including change of medication or prescription of additional medication may be require to control blood pressure. Discussing potential changes to blood pressure therapies may be warranted. This message was generated by the COACH tool and actively sent by the patient.</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by mattStorer** [comment]
the meat of this is added into COACH so that certain tokens are now permitted to be added into contact messages.  per the commit message, the following tokens can be written into contact messages and this is what they'll be replaced with:

`{readings}` : the number of home BP readings collected within the last 30 days;
`{days}` : the number of days over which the specified readings were collected;
`{systolic}` : the average systolic BP for ALL readings (home, office, etc.) using the same logic as what's employed in the UI;
`{diastolic}` : the average diastolic BP for ALL readings (home, office, etc.) using the same logic as what's employed in the UI.

**Comment by mattStorer** [comment]
leaving this ticket open until an appropriate care team message is crafted and linked to a recommendation endpoint

**Comment by ghumman96** [comment]
Not at goal message is edited with the list format https://ohsuitg-my.sharepoint.com/:w:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/Mockups%20and%20Screenshots/Not%20at%20Goal%20Message%20to%20provider.docx?d=w61ace52c4391427784b71dc8779028b2&csf=1&web=1&e=gjTczi

**Comment by ghumman96** [comment]
[COACH Auto generated messages.docx](https://github.com/OHSUCMP/coach/files/13217945/COACH.Auto.generated.messages.docx)
Here are the edited messages

**Comment by mattStorer** [comment]
add a separate token {meds} that generates a comma separated list of the participant's current anti-hypertensive medications, that can be injected into care team messages

**Comment by mattStorer** [comment]
added new `{meds}` token that can be included in contact messages, which will be replaced with a comma-separated list of the participant's active anti-hypertensive medications, or the literal text "(none)" if no such medications are currently being taken.

**Comment by mattStorer** [comment]
add some basic framework to provide a way to store `aboveText` and `belowText` data alongside a care team message in the database.  these fields should be displayed above and below the care team message input on that screen

**Comment by aeyates** [comment]
https://ohsuitg-my.sharepoint.com/:w:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/CDS%20Cards/COACH%20Auto%20generated%20messages.docx?d=w4fe2feef6d2142d79b7d76ccfcbce265&csf=1&web=1&e=ZImeSl

**Comment by ghumman96** [comment]
The document linked above is updated and ready

**Comment by mattStorer** [comment]
updates are completed in the app and database side of things.  @aeyates have you made the requested edits to the recommendation text?  if so, this ticket is probably dev complete.

**Comment by aeyates** [comment]
Yes, recommendation changes are done.
