### ISSUE TITLE
High BP Logic

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#96]
This issue is a high-BP corollary to issue #81 for Low BP Logic.

If a user enters systolic >= 180 or diastolic >= 120 in the BP entry screen, it is understood that we want to redirect the user to the homepage and rerun recommendations, which should trigger an AE workflow endpoint that generates a card that instructs the user to take another reading.

Where this differs, perhaps, is in the automatic generation of an AdverseEvent resource.  In the event that the user enters two consecutive low BP readings, we are to generate a Hypotension AdverseEvent and persist that within COACH.  There exists AdverseEvent codings in COACH that relate to Hypotension to facilitate this, but none exist that relate to dangerously high BPs.

How does processing a dangerously high BP reading differ in this workflow?  Is it identical, but mirrored, inversed, relative to the Low BP logic represented in #81?  Or are there variations on how we want to process dangerously high BP readings in this context?

**Comment by mattStorer** [comment]
notes from Dave 10/6:

> [8:50 AM] David Dorr
>     No need to create an AE for high blood pressure. An adverse event is something due to treatment, whereas a high BP is the clinical condition we are trying to address.
> 
> ​[8:51 AM] David Dorr
>     That said, we should probably have a safety plan for high blood pressures with outreach. Given the de-identification of the system, I need to think through the options there.
>

**Comment by mattStorer** [comment]
updated COACH to perform the desired actions.  note that if there are changes that need to be made to the recommendation logic to process the recent high BP reading in order to inform the user that they should take another one, that logic will still need to be built out (but I will let @aeyates take care of that part).

**Comment by aeyates** [comment]
I don't understand what changes were made? Just a redirect to recommendations page on a high BP reading? The recommendations already handle different language when there's one high BP versus two: https://github.com/OHSUCMP/htnu18ig/issues/176. But this isn't an "AE workflow endpoint" and isn't related to adverse events.

**Comment by mattStorer** [comment]
> I don't understand what changes were made? Just a redirect to recommendations page on a high BP reading? The recommendations already handle different language when there's one high BP versus two: [OHSUCMP/htnu18ig#176](https://github.com/OHSUCMP/htnu18ig/issues/176). But this isn't an "AE workflow endpoint" and isn't related to adverse events.

yes that's right.  if the most recent BP reading the user enters is high or low, they receive an alert message telling them of that fact, and that they're going to be redirected to the home page to receive updated recommendations.

I don't recall if there's a recommendation workflow endpoint that instructs the user to take an additional reading as a result of receiving that high or low reading recently recorded.  maybe nothing needs to be done?  seeking verification one way or the other.

**Comment by aeyates** [comment]
We've never handled a low BP, so that would be a new workflow endpoint. But yes, the recommendations already handle both one and two high BPs in a row.

**Comment by mattStorer** [comment]
also, it's probably worth noting that the most recent BP reading entered into the BP entry screen may not actually be their most recent reading, since readings can be entered out of chronological order.  the system presently checks only the values entered without performing a greater chronological-sequence check to see if the most recent reading they just entered is actually the chronologically most recent reading out of all of those that have been collected for the user.

so if a user is entering BPs from a week ago, and there have been, say, dozens of readings entered with more recent timestamps, that week-old BP reading may trigger the high or low BP redirect-to-home.  I think this is desired behavior?  alternatively, if the system should only ever consider the most recent chronological reading irrespective of when it was entered, that could wind up redirecting over and over again which would be really annoying.

**Comment by aeyates** [comment]
Hmm, well the recommendation is only going to consider the most recent BPs chronologically. It wouldn't make sense to provide them warnings for old BPs when their readings have gone down since then. So if you redirect based on an older BP, the recommendations will rerun but nothing will change. Also, we need to make sure that the graph logic is all based on chronological BPs - otherwise we'll have a disconnect with the recommendations. So I don't think it's desired behavior to redirect when an old BP is entered, since in theory nothing on the home page should have changed. I would opt for a hybrid approach. Redirect if and only if the BPs entered are the most recent AND they are high. This is the only condition that might trigger graph and recommendation changes significant enough to warrant the action.

**Comment by mattStorer** [comment]
seems the simplest solution to the redirect question is to redirect only if a) the most recent reading entered is high or low, AND b) the most recent reading is *also* the most recent chronologically.  I think that would do the trick.

**Comment by mattStorer** [comment]
updated to ensure that user is only redirected to the home screen following the posting of home BP readings IF the most recent posted reading is high or low, AND the reading is the most recent out of all readings (home and office).  this will ensure that the redirect only responds to truly current data, as desired.

**Comment by aeyates** [comment]
Reviewed with Matt. We think this is done.
